# Generated by Django 3.2.9 on 2021-11-11 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='log',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='brands'),
            preserve_default=False,
        ),
    ]
