# Generated by Django 3.2.9 on 2021-11-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='price',
        ),
        migrations.AddField(
            model_name='variant',
            name='landing_price',
            field=models.IntegerField(null=True, verbose_name='Landing price'),
        ),
        migrations.AddField(
            model_name='variant',
            name='mrp',
            field=models.IntegerField(null=True, verbose_name='M.R.P'),
        ),
        migrations.AddField(
            model_name='variant',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
