# Generated by Django 3.2.9 on 2021-11-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='storage',
            field=models.CharField(choices=[('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('128GB', '128GB'), ('512GB', '512GB')], max_length=20),
        ),
    ]
