# Generated by Django 3.2.9 on 2021-11-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'ram', 'storage', 'color')},
        ),
    ]
