# Generated by Django 3.2.9 on 2021-11-11 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('BLACK', 'BLACK'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(choices=[('8GB', '8GB'), ('8GB', '8GB'), ('8GB', '8GB'), ('8GB', '8GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('128GB', '128GB'), ('512GB', '512GB')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(choices=[('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB'), ('12GB', '12GB')], max_length=20),
        ),
    ]
