# Generated by Django 3.2.9 on 2021-11-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211125_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='offer',
        ),
    ]
