version: "3"
services:
  m3-mobiles:
    build:
      context: .
    volumes:
     - m3-mobiles-assets:/app/assets
     - m3-mobiles-media:/app/media
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - VERIFICATION_SID=${VERIFICATION_SID}
      - RAZOR_KEY_ID=${RAZOR_KEY_ID}
      - RAZOR_KEY_SECRET=${RAZOR_KEY_SECRET}
    depends_on:
      - db

  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
     - m3-mobiles-db:/var/lib/postgresql/data

  nginx:
    build: ./nginx 
    ports:
      - 80:80
    volumes:
      - m3-mobiles-assets:/app/assets
      - m3-mobiles-media:/app/media
    depends_on:
      - m3-mobiles
    
volumes:
  m3-mobiles-assets:
  m3-mobiles-media:
  m3-mobiles-db:
