apiVersion: v1
kind: Secret
metadata:
  name: m3-mobiles-secret
type: Opaque
data:
  secret-key: ZmRzZmRzZg==
  debug: VHJ1ZQ==
  db-name: cG9zdGdyZXM=
  db-user: cG9zdGdyZXM=
  db-password: cG9zc3dvcmQ=
  db-port: NTQzMgo=
  twilio-account-sid: QUM3ZDQ4NmQ5MGRjNWRiZTc0ZjZiODc1NGNhMDdkNzE5MQ==
  twilio_auth_token: NGZlZTNkYzIxNGU5NWY1ZDg2NDM3MjUyOTgyODk3NmI=
  verification-sid: VkE0MTU5OTFiZGRjYjE4N2MzYjA0Y2ExZjhmMzAyNTAyMQ==
  razor-key-id: cnpwX3Rlc3RfdklFa1VjaVVQSUtEeno=
  razor-key-secrete: ZldtZGtLNHdvWFZlTXZoVFBhSjF2dFB6
