# Generated by Django 3.2.9 on 2021-11-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon_discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
