# Generated by Django 3.2.9 on 2021-11-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandoffer',
            old_name='offer',
            new_name='discount_offer',
        ),
        migrations.RenameField(
            model_name='productoffer',
            old_name='offer',
            new_name='discount_offer',
        ),
        migrations.RenameField(
            model_name='variantoffer',
            old_name='offer',
            new_name='discount_offer',
        ),
    ]
