# Generated by Django 3.2.9 on 2021-11-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_offer'),
        ('brand', '0003_remove_brand_offer'),
        ('offer', '0002_auto_20211126_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandoffer',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='variantoffer',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variant'),
        ),
    ]
