# Generated by Django 3.2.9 on 2021-11-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20211126_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantoffer',
            name='variant',
        ),
    ]
