# Generated by Django 3.2.9 on 2021-11-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_offer'),
        ('offer', '0005_variantoffer_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantoffer',
            name='variant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variant'),
        ),
    ]
