# Generated by Django 3.2.9 on 2021-11-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_offer'),
        ('brand', '0003_remove_brand_offer'),
        ('offer', '0006_alter_variantoffer_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoffer',
            name='brand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
