# Generated by Django 3.2.9 on 2021-11-27 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_offer'),
        ('brand', '0003_remove_brand_offer'),
        ('offer', '0008_auto_20211126_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoffer',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='brandoffer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='variantoffer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variantoffer',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.variant'),
        ),
    ]
