# Generated by Django 3.2.9 on 2021-11-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_coupon_redeemedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.PositiveIntegerField(help_text='Offer in percentage', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
