# Generated by Django 3.2.9 on 2021-11-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_auto_20211129_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
