# Generated by Django 3.2.9 on 2021-12-06 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('house_no', models.CharField(max_length=255, verbose_name='House no/Building/Company')),
                ('area', models.CharField(max_length=255, verbose_name='Area/Street/Sector/Village')),
                ('landmark', models.CharField(blank=True, max_length=50)),
                ('town', models.CharField(max_length=50, verbose_name='Town/City')),
                ('state', models.CharField(max_length=50)),
                ('pin', models.PositiveIntegerField()),
                ('type', models.CharField(help_text='Example:- Home, Office, etc', max_length=50, null=True, verbose_name='Address Type')),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
