# Generated by Django 3.2.9 on 2021-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(help_text='Example:- Home, Office, etc', max_length=50, null=True, verbose_name='Address Type'),
        ),
    ]
