# Generated by Django 3.2.9 on 2021-11-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
