# Generated by Django 3.2.9 on 2021-11-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211123_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='tracking_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
