# Generated by Django 3.2.9 on 2021-11-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20211124_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='tracking_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
