# Generated by Django 3.2.9 on 2021-11-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderproduct_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
