# Generated by Django 3.2.9 on 2021-11-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_price_orderproduct_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['-updated_at']},
        ),
    ]
